org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
android.enableBuildCache=false
SDK_REGISTRY_TOKEN=***REMOVED***J1IjoibmFzdGVjc29sIiwiYSI6ImNtMm9tYW1kMTBoemkyanMzM2U4eDR4eHUifQ.PqywfCYGKYdtNmrZ1PsKuw
