org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=/Users/sulemanniazzi/Library/Java/JavaVirtualMachines/corretto-17.0.14/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
android.enableBuildCache=false
SDK_REGISTRY_TOKEN=sk.eyJ1IjoibmFzdGVjc29sIiwiYSI6ImNtMm9tYW1kMTBoemkyanMzM2U4eDR4eHUifQ.PqywfCYGKYdtNmrZ1PsKuw
android.experimental.enable16kPageSizeSupport=true
android.suppressUnsupportedCompileSdk=36

# remove or update this line since 1.18.0 needs AGP 8.9.1
# the force in build.gradle was pinning 1.17.0, which is correct