org.gradle.jvmargs=-Xmx4G
org.gradle.java.home=/Users/sulemanniazzi/Library/Java/JavaVirtualMachines/corretto-17.0.14/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
android.enableBuildCache=false
SDK_REGISTRY_TOKEN=sk.eyJ1IjoibmFzdGVjc29sIiwiYSI6ImNtMm9tYW1kMTBoemkyanMzM2U4eDR4eHUifQ.PqywfCYGKYdtNmrZ1PsKuw
