// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpPMlIWrwGvEIB7mgTMS9iU5_hp04ASUw',
    appId: '1:849512939836:web:b76e8d3fbb21db7983de39',
    messagingSenderId: '849512939836',
    projectId: 'nashr-b93a9',
    authDomain: 'nashr-b93a9.firebaseapp.com',
    storageBucket: 'nashr-b93a9.firebasestorage.app',
    measurementId: 'G-LY7NFLJ3LV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjwjOFEmH8x-gZzAvG5P_Q2eFwEHmeTi8',
    appId: '1:849512939836:android:cca7536afcf6ae0483de39',
    messagingSenderId: '849512939836',
    projectId: 'nashr-b93a9',
    storageBucket: 'nashr-b93a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqU4IEV0Yimp2ppXGUyfFAOqQH97d5QVE',
    appId: '1:849512939836:ios:9f5317da6b16ae6083de39',
    messagingSenderId: '849512939836',
    projectId: 'nashr-b93a9',
    storageBucket: 'nashr-b93a9.firebasestorage.app',
    iosBundleId: 'com.nastecsol.nashr',
  );
}
