name: CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

  push:
    branches:
      - releases_ios
      - releases_android

jobs:
  flutter_test:
    name: Run Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter --version
      - run: flutter test

  build_ios_app:
    name: Build Flutter App (iOS)
    if: github.ref == 'refs/heads/releases_ios'
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean

      - name: Set ENV variable
        run: echo "ENV=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV

      - name: Build iOS App
        run: |
          flutter build ios --no-codesign --dart-define=ENV=$ENV
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r app.ipa Payload

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: iOS_App_Build
          path: build/ios/iphoneos/app.ipa

  build_android_app:
    name: Build Flutter App (Android)
    if: github.ref == 'refs/heads/releases_android'
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set Java for Gradle
        run: echo "org.gradle.java.home=${JAVA_HOME_17_X64}" >> android/gradle.properties

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter clean

      - name: Set ENV variable
        run: echo "ENV=${{ github.event.inputs.environment || 'dev' }}" >> $GITHUB_ENV

      - name: Build APK
        run: flutter build apk --release --dart-define=ENV=$ENV

      - name: Upload Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android_App_Build
          path: build/app/outputs/flutter-apk/app-release.apk

  notify_slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: [build_ios_app, build_android_app]
    if: always()
    steps:
      - name: Set Slack Color
        id: slackcolor
        run: |
          if [[ "${{ needs.build_ios_app.result }}" == "success" && "${{ needs.build_android_app.result }}" == "success" ]]; then
            echo "color=#2cde04" >> $GITHUB_OUTPUT
          else
            echo "color=#de2c2c" >> $GITHUB_OUTPUT
          fi

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: flutter-builds
          SLACK_COLOR: ${{ steps.slackcolor.outputs.color }}
          SLACK_ICON: https://github.com/ED209Repo/AnyPick/blob/main/images/mainlogo.png?size=48
          SLACK_MESSAGE: '🚀 New build for Nas-HR completed for ${{ github.event.inputs.environment || 'dev' }} environment.'
          SLACK_TITLE: Flutter CI Build
          SLACK_USERNAME: Danial
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

